# modified and borrowed from https://github.com/domdfcoding/pynist
name: Build manylinux Wheels

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: "manylinux2014"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Set up Python 🐍
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install twine tox tox-gh-actions
      - name: Build manylinux2014 Python wheels 🎡
        uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2014_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
          package-path: ''
          pip-wheel-args: '--no-deps'
      - name: Upload Artifacts 🚀
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/
      - name: "Run Tests"
        run: |
          PYVERSIONS=("36" "38")
          for PYVERSION in "${PYVERSIONS[@]}"; do
            for whl in wheelhouse/ppmd_cffi-*-cp${PYVERSION}-cp${PYVERSION}*-manylinux*.whl; do
              python -m tox -r -e py${PYVERSION} --installpkg "$whl"
            done
          done
      - name: Publish distribution 📦 to Test PyPI
        if: startsWith(github.event.ref, 'refs/heads/master')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: wheelhouse/