name: Publish Python 🐍 wheel distributions 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - main
      - releases/*
    tags:
      - v*

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pep517 and twine
      run: python -m pip install pep517 --user
    - name: Build a wheel package
      run: python -m pep517.build --binary --out-dir dist/ ./
    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(github.event.ref, 'refs/heads/main')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.testpypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
